config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :posts do
    resources :comments
  end

  resources :posts do
    resources :tags
  end

  resources :tags do
    resources :posts
  end

  resources :schedules

  resources :team_stats

  namespace :api do
    resources :posts, defaults: { format: 'json' }
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :presence => true
  has_many :comments
  has_and_belongs_to_many :tags

end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    respond_to :json

    def index
      @posts = Post.all
      respond_with @posts
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  def index
    @posts = Post.all.paginate(page: params[:page], per_page: 2)
    render :index
  end

  # GET /posts/1
  def show
    @posts = Post.all
    @post = Post.find(params[:id])
    render :show
  end

  # GET /posts/new
  def new
    @post = Post.new
    render :new
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:notice] = "Post added!"
      respond_to do |format|
        format.js
        format.html {redirect_to posts_path}
      end
    else
      flash[:alert] = "There was a problem. Your post was not added."
      respond_to do |format|
        format.js
        format.html {render :new}
      end
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    respond_to do |format|
      format.js
      format.html {render :edit}
    end
  end

  # PATCH/PUT /posts/1
  def update
    if params[:remove_tag]
      @tag = Tag.find(params[:tag_id])
      @post = Post.find(params[:id])
      @post.tags.delete(@tag)
      redirect_to post_path(@post)
    elsif @post.update(post_params)
      flash[:notice] = 'Post was successfully updated.'
      redirect_to post_path
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post = Post.find(params[:id])

    #delete all post.tags  may need to find all tags first.

    @post.destroy
    @post.tags.delete

    flash[:notice] = 'Post was successfully deleted.'
    redirect_to posts_url
  end

  private
    #Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    #Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/create.js.erb
$("form").remove();
$("#new_post_link").show();
$(".post_messages").append("<h2><%= link_to post.title, post %></h2><p><%= friendly_date post.created_at %></p> <p><%= post.body %></p>")

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/edit.js.erb
$("#edit_post_link").hide();
$("#post_show_message").append("<%= j render 'form' %>")

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>
<article class="post_messages">
  <%= will_paginate @posts %>
    <% @posts.each do |post| %>
      <h2><%= link_to post.title, post %></h2>
      <p><%= friendly_date post.created_at %></p>
      <p><%= truncate(post.body, :length => 150) %></p>
      <p>
      </p>
    <% end %>
  <%= will_paginate @posts %>
</article>
<br>

<% if current_user  %>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-success', remote: true, id: "new_post_link" %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/new.js.erb
$("#new_post_link").hide();
$(".post_messages").append("<%= j render 'form' %>")

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div id="post_show_message">

<h2 >
  <%= @post.title %>
</h2>
<p><%= @post.body %></p>
</div>
<p>
  <% if current_user && current_user.admin %>
    <%= link_to 'Edit Post', edit_post_path(@post), class: 'btn btn-info', remote: true, id: 'edit_post_link' %>
    <%= link_to 'Delete Post', @post, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>

<h3>Tags:</h3>
<div class="tag_messages">
  <% @post.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag)  %>
      <% if current_user && current_user.admin %>
      <br>
        <%= link_to 'Edit Tag', edit_post_tag_path(@post, tag), class: 'btn btn-info', remote: true, id: "edit_tag_link" %>
        <%= link_to 'Delete Tag', post_tag_path(@post, tag, remove_tag: "true"), class: 'btn btn-danger', data: {confirm: "Are you sure?", method: "delete"} %></li>
      <% end %>
      <br>
      <br>
  <% end %>
</div>
  <div id="tag_show_message">
  </div>


  <% if current_user %>
    <%= link_to 'New Tag', new_post_tag_path(@post), class: 'btn btn-success', remote: true, id: "new_tag_link"%>
  <% end %><br>
  <br>

<h3>Comments</h3>
<article class="comment_messages">
  <% @post.comments.each do |comment| %>
    <div id="comment_show_message">
      <%= comment.body  %>
    </div>
    <br>
    <% if current_user && current_user.admin %>
      <%= link_to 'Edit Comment', edit_post_comment_path(@post, comment), class: 'btn btn-info',remote: true, id: "edit_comment_link" %>
      <%= link_to 'Delete Comment', post_comment_path(@post, comment), class: 'btn btn-danger', data: {confirm: "Are you sure?"}, method: "delete"%>
    <% end %>
    <br>
  <% end %>
</article>
  <br>



<% if current_user %>
  <%= link_to 'New Comment', new_post_comment_path(@post), class: 'btn btn-success',remote: true, id: "new_comment_link" %>
<% end %>

app/views/posts/update.js.erb
$("form").remove();
$("#edit_post_link").show();
$("#post_show_message").replaceWith("<h2><%= link_to post.title, post %></h2><p><%= friendly_date post.created_at %></p> <p><%= post.body %></p>")