config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :posts do
    resources :comments
  end

  resources :posts do
    resources :tags
  end

  resources :tags do
    resources :posts
  end

  resources :schedules

  resources :team_stats

  namespace :api do
    resources :posts, defaults: { format: 'json' }
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hockey Site</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to image_tag("hockey.jpg"), posts_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "Team Stats", team_stats_path %></li>
        <li><%= link_to "Schedule", schedules_path %></li>

      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <!-- This is currently empty -->
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.username %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
    <% if flash[:notice] -%>
      <div class = "alert alert-success"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] -%>
      <div class = "alert alert-danger"><%= flash[:alert] %></div>
    <% end %>
  </div>

<div class="container">
  <%= yield %>
</div>


</body>
</html>